name: Format

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format -y
      # Catkin lint is installed but not included in pre-commit
      - name: Install catkin_lint
        uses: DavidPL1/install-catkin_lint-action@ros2
      - uses: pre-commit/action@v3.0.1
        id: precommit
      - name: Upload pre-commit changes
        if: failure() && steps.precommit.outcome == 'failure'
        uses: rhaschke/upload-git-patch-action@main
        with:
          name: pre-commit
