MujocoPlugins:
  - type: mujoco_ros_laser/LaserPlugin
    sensors:
    - site_attached: laser_site
      frame_id: scan
      visualize: true
      update_rate: 10.
      min_range: 0.1
      max_range: 30.
      range_resolution: 0.01
      angular_resolution: 0.02
      min_angle: -1.57
      max_angle: 1.57
